import { Account, Card, Transaction, VantisUser } from "./types";

export const seedUser: VantisUser = {
  id: "u_demo",
  name: "Amara Okafor",
  email: "demo@vantis.bank",
  initials: "AO",
  phone: "+1 (415) 555-0148",
  address: "148 Ferry Street, San Francisco, CA",
  image: "",
  role: "user",
  locked: false,
  createdAt: "2023-02-11T10:00:00.000Z",
};

export const seedAccounts: Account[] = [
  {
    id: "acc_checking",
    name: "Everyday Checking",
    number: "4821093157",
    balance: 766000,
    currency: "USD",
    type: "checking",
  },
  {
    id: "acc_savings",
    name: "Growth Savings",
    number: "7734215608",
    balance: 24310.9,
    currency: "USD",
    type: "savings",
    apy: 4.25,
  },
];

export const seedCards: Card[] = [
  {
    id: "card_1",
    label: "Everyday Card",
    holder: "Amara Okafor",
    last4: "4821",
    expiry: "09/29",
    type: "physical",
    network: "visa",
    frozen: false,
    limit: 5000,
    spent: 1284.32,
    color: "gold",
    accountId: "acc_checking",
  },
  {
    id: "card_2",
    label: "Subscriptions Virtual",
    holder: "Amara Okafor",
    last4: "1190",
    expiry: "03/28",
    type: "virtual",
    network: "mastercard",
    frozen: true,
    limit: 500,
    spent: 89.0,
    color: "teal",
    accountId: "acc_checking",
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: "tx_1",
    title: "Project materials from China",
    category: "Equipment",
    amount: -161000,
    date: "2026-07-22T09:15:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "China Supplier",
    status: "completed",
  },
  {
    id: "tx_2",
    title: "Food",
    category: "Food & Drink",
    amount: -1000,
    date: "2026-07-21T14:02:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Local Restaurant",
    status: "completed",
  },
  {
    id: "tx_3",
    title: "Hotel payment",
    category: "Housing",
    amount: -7000,
    date: "2026-07-20T11:22:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Grand Hotel",
    status: "completed",
  },
  {
    id: "tx_4",
    title: "Flight ticket",
    category: "Travel",
    amount: -750,
    date: "2026-07-20T16:45:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Airline",
    status: "completed",
  },
  {
    id: "tx_5",
    title: "Nia Studio Rent",
    category: "Housing",
    amount: -1850,
    date: "2026-07-18T09:15:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Nia Studio Rentals",
    status: "completed",
  },
  {
    id: "tx_6",
    title: "From Alex Morgan",
    category: "Transfer",
    amount: 620,
    date: "2026-07-19T14:02:00.000Z",
    accountId: "acc_checking",
    direction: "credit",
    counterparty: "Alex Morgan",
    status: "completed",
  },
  {
    id: "tx_7",
    title: "Kaya Coffee Roasters",
    category: "Food & Drink",
    amount: -8.5,
    date: "2026-07-16T08:41:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Kaya Coffee Roasters",
    status: "completed",
  },
  {
    id: "tx_8",
    title: "Payroll — Halcyon Labs",
    category: "Income",
    amount: 4200,
    date: "2026-07-15T06:00:00.000Z",
    accountId: "acc_checking",
    direction: "credit",
    counterparty: "Halcyon Labs Inc.",
    status: "completed",
  },
  {
    id: "tx_9",
    title: "Savings Round-Up",
    category: "Transfer",
    amount: -75,
    date: "2026-07-14T20:00:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Growth Savings",
    status: "completed",
  },
  {
    id: "tx_10",
    title: "Ondo Electric Co.",
    category: "Utilities",
    amount: -142.18,
    date: "2026-07-12T11:22:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Ondo Electric Co.",
    status: "completed",
  },
  {
    id: "tx_11",
    title: "To Femi Balogun",
    category: "Transfer",
    amount: -300,
    date: "2026-07-10T17:47:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Femi Balogun",
    status: "pending",
  },
  {
    id: "tx_12",
    title: "Interest Payment",
    category: "Interest",
    amount: 86.12,
    date: "2026-07-01T00:00:00.000Z",
    accountId: "acc_savings",
    direction: "credit",
    counterparty: "Vantis Bank",
    status: "completed",
  },
  {
    id: "tx_13",
    title: "Civil Engineering Tools — Total Station",
    category: "Equipment",
    amount: -4200,
    date: "2026-07-09T10:30:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "SurveyTech Supplies",
    status: "completed",
  },
  {
    id: "tx_14",
    title: "Civil Engineering Tools — Laser Level",
    category: "Equipment",
    amount: -1850,
    date: "2026-07-08T14:22:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "BuildRight Tools",
    status: "completed",
  },
  {
    id: "tx_15",
    title: "Civil Engineering Tools — Theodolite",
    category: "Equipment",
    amount: -3100,
    date: "2026-07-07T09:10:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "Precision Instruments Ltd.",
    status: "completed",
  },
  {
    id: "tx_16",
    title: "Civil Engineering Tools — Compaction Tester",
    category: "Equipment",
    amount: -980,
    date: "2026-07-06T16:45:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "SoilTest Engineering",
    status: "completed",
  },
  {
    id: "tx_17",
    title: "Site Plan Prints — Downtown Bridge",
    category: "Services",
    amount: -320,
    date: "2026-07-05T11:05:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "PrintWorks Drafting",
    status: "completed",
  },
  {
    id: "tx_18",
    title: "Consulting Fee — Structural Review",
    category: "Income",
    amount: 7500,
    date: "2026-07-04T08:00:00.000Z",
    accountId: "acc_checking",
    direction: "credit",
    counterparty: "Apex Infrastructure",
    status: "completed",
  },
  {
    id: "tx_19",
    title: "AutoCAD License Renewal",
    category: "Software",
    amount: -285,
    date: "2026-07-03T00:00:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "AutoDesk",
    status: "completed",
  },
  {
    id: "tx_20",
    title: "Civil Engineering Tools — Drone Survey Kit",
    category: "Equipment",
    amount: -5200,
    date: "2026-07-02T09:30:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "AeroMap Tech",
    status: "completed",
  },
  {
    id: "tx_21",
    title: "Civil Engineering Tools — Concrete Testing Kit",
    category: "Equipment",
    amount: -1450,
    date: "2026-07-01T11:15:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "MatTest Solutions",
    status: "completed",
  },
  {
    id: "tx_22",
    title: "Civil Engineering Tools — Safety Helmets & Vests",
    category: "Equipment",
    amount: -620,
    date: "2026-06-30T08:45:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "SiteSafe Supplies",
    status: "completed",
  },
  {
    id: "tx_23",
    title: "Civil Engineering Tools — Total Station Battery Pack",
    category: "Equipment",
    amount: -340,
    date: "2026-06-29T14:20:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "SurveyTech Supplies",
    status: "completed",
  },
  {
    id: "tx_24",
    title: "Consulting Fee — Road Alignment Design",
    category: "Income",
    amount: 12000,
    date: "2026-06-28T10:00:00.000Z",
    accountId: "acc_checking",
    direction: "credit",
    counterparty: "Metro Infrastructure",
    status: "completed",
  },
  {
    id: "tx_25",
    title: "Civil Engineering Tools — Laser Distance Measurer",
    category: "Equipment",
    amount: -480,
    date: "2026-06-27T16:30:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "BuildRight Tools",
    status: "completed",
  },
  {
    id: "tx_26",
    title: "Civil Engineering Tools — Soil Boring Equipment",
    category: "Equipment",
    amount: -2100,
    date: "2026-06-26T09:00:00.000Z",
    accountId: "acc_checking",
    direction: "debit",
    counterparty: "GeoDrill Pro",
    status: "completed",
  },
];
